version: '2'
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.2"
    command: "etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379

  kubernetes:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.9.2"
    depends_on:
      - "etcd"
    command: "/hyperkube apiserver --insecure-bind-address=0.0.0.0 --etcd-servers=http://etcd:2379 --service-cluster-ip-range=10.0.0.0/16"
    ports:
      - 8080:8080

  example-controller:
    image: "example-controller"
    depends_on:
      - "kubernetes"
    command:
      sh -c "
      /go/src/github.com/intel/crd-reconciler-for-kubernetes/resources/wait-port kubernetes 8080 &&
      /go/bin/example-controller
        --kubeconfig=/go/src/github.com/intel/crd-reconciler-for-kubernetes/resources/config"
    privileged: true # required for debugging

  test:
    image: "crd-reconciler-for-kubernetes"
    depends_on:
      - "kubernetes"
    environment:
      - KUBECONFIG=/go/src/github.com/intel/crd-reconciler-for-kubernetes/resources/config
    command: "sleep inf"
