FROM golang:1.8.3

RUN apt-get update && apt-get install -y netcat
RUN go get -u github.com/golang/dep/cmd/dep
RUN mkdir -p /go/src/github.com/NervanaSystems
ADD . /go/src/github.com/NervanaSystems/kube-controllers-go
WORKDIR /go/src/github.com/NervanaSystems/kube-controllers-go
RUN rm -rf vendor
RUN dep ensure
