version: '2'
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.2"
    command: "etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379

  kubernetes:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.7.3"
    depends_on:
      - "etcd"
    command: "/hyperkube apiserver --insecure-bind-address=0.0.0.0 --etcd-servers=http://etcd:2379 --service-cluster-ip-range=10.0.0.0/16"
    ports:
      - 8080:8080

  stream-prediction-controller:
    image: "stream-prediction-controller:v0.1.0"
    depends_on:
      - "kubernetes"

  test:
    image: "kube-controllers-go:v0.1.0"
    depends_on:
      - "kubernetes"
      - "stream-prediction-controller"
    command: "sleep inf"
