FROM golang:1.8.3

RUN apt-get update && apt-get install -y netcat python-pip
RUN pip install jsonschema
RUN go get -u github.com/golang/dep/cmd/dep
RUN mkdir -p /go/src/github.com/NervanaSystems
ADD . /go/src/github.com/NervanaSystems/kube-controllers-go
WORKDIR /go/src/github.com/NervanaSystems/kube-controllers-go
RUN make install-linter
RUN rm -rf vendor
# in order to build each of the controllers, the vendored deps need to be on
# the shared gopath.
RUN dep ensure && cp -R vendor/* /go/src/ && rm -rf *
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl && cp ./kubectl /usr/local/bin/kubectl
