#!/bin/bash
#
# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: EPL-2.0
#

set -o nounset -o errexit -o pipefail
GODEBUGGER=${GODEBUGGER:=gdb}

usage () 
{
  echo -e "Usage: $0 attach processname\n" \
'attach:\n' \
'  \033[4ma\033[0mttach   attach to the process with the given name\n'
}

attach ()
{
  pname=${1:0:15}
  pid=$(pgrep $pname)
  while [ -z "$pid" ]; do
    echo "waiting for $1 process to start..."
    sleep 1
    pid=$(pgrep $pname)
  done
  case "$GODEBUGGER" in
    dlv)
      dlv attach $pid
      ;;
    gdb)
      gdb --quiet -iex "set auto-load safe-path /usr/local/go/src/runtime/runtime-gdb.py" -pid $pid
      ;;
    *)
      echo "unknown debugger $GODEBUGGER"
      ;;
  esac
}

commands () 
{
  if [ $# = "0" ]; then
    usage
    exit 1
  fi
  local exitcode=0
  while :
  do
    case "$1" in
      a | at | att | atta | attac | attach)
        shift 1
        attach "$@"
        exitcode=$?
        break
        ;;
      *)
        echo "**** unknown argument $1 ****"
        exitcode=1
        break
        ;;  
    esac
  done
  exit $exitcode
}
commands $*
